[package]
name = "rust_heap"
version = "0.1.0"
authors = ["Blake Loring <blake@parsed.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.8.3"
